#!/bin/dash
website="$1"
regex="$2"
email="$3"

if test "$#" != 3
then
    echo "Usage: $0 <website> <regex> <email>" 1>&2
fi

while true 
do
    if curl --silent "$website" | grep -E "$regex" >/dev/null
    then
        echo "Generated by $0"| echo mail -s "$website now matches $regex" "$email"
        exit 0
    else 
        echo -n .
    fi
    sleep 3
done 